import { Incident, Responder, CustomWidget } from "./types";

export const COIMBATORE_LANDMARKS = [
  { name: "RS Puram", lat: 11.0115, lng: 76.9450, desc: "West Zone Residential/Commercial Hub" },
  { name: "Gandhipuram", lat: 11.0183, lng: 76.9638, desc: "Central Transit & Cross Cut Retail Sector" },
  { name: "Ukkadam Lake", lat: 10.9875, lng: 76.9625, desc: "South Lake & Critical Catchment Basin" },
  { name: "Peelamedu", lat: 11.0289, lng: 77.0264, desc: "East IT & Educational Corridor" },
  { name: "Singanallur", lat: 11.0022, lng: 77.0210, desc: "South-East Junction & Noyyal Spillway" },
  { name: "Town Hall", lat: 10.9964, lng: 76.9602, desc: "Heritage Center & Corporation HQ" },
  { name: "Saravanampatti", lat: 11.0785, lng: 76.9984, desc: "North IT Tech Zone" }
];

export const TRANSLATIONS = {
  en: {
    title: "CiviqAI Coimbatore",
    subtitle: "City Decision Intelligence & Incident Command System",
    role: "Current Role",
    dispatcher: "Dispatcher (Command)",
    responder: "Field Unit (Noyyal Patrol)",
    admin: "System Administrator",
    language: "Language",
    offlineMode: "Offline Mode",
    online: "Online & Synced",
    offline: "Offline State",
    syncQueue: "Sync Queue",
    syncSuccess: "Cloud Synchronization successful!",
    incidents: "Emergencies",
    activeIncidents: "Active Incidents",
    reported: "Reported",
    dispatched: "Dispatched",
    onScene: "On-Scene",
    resolved: "Resolved",
    severity: "Severity",
    critical: "Critical",
    high: "High",
    medium: "Medium",
    low: "Low",
    category: "Category",
    flooding: "Water Logging / Flood",
    fire: "Fire Emergency",
    road_block: "Road Blockage",
    medical: "Medical Support",
    power_outage: "Power Grid Cut",
    other: "Other Incident",
    location: "Location / Landmark",
    addIncident: "File New Emergency Report",
    incidentTitle: "Incident Title",
    description: "Detailed Description",
    assignedTo: "Assigned Squad",
    reportNow: "Submit Dispatch Report",
    useGPS: "Fetch Live GPS Coords",
    aiCore: "CiviqAI Decision Core",
    aiPlaceholder: "Ask Gemini: 'Recommend dispatch for Peelamedu' or 'Noyyal flood threat'...",
    askAI: "Consult AI Commander",
    analytics: "Coimbatore Performance Analytics",
    chartsTitle: "Live Operations Telemetry",
    widgets: "Active Monitor Widgets",
    chatTitle: "Tactical Operations Chat",
    chatPlaceholder: "Type message to team...",
    send: "Send",
    exportPDF: "Export Situation Report (PDF)",
    notifications: "Urgent Dispatch Alerts",
    noIncidents: "No incidents logged in this status.",
    unassigned: "Unassigned Squad",
    allWidgets: "Corporation Dashboard Widgets",
    saveWidgetSettings: "Save Widget Configuration",
    mapLegend: "Interactive Map of Coimbatore",
    weatherWidget: "Noyyal Watershed Weather",
    recentActivity: "Central Command Logs",
    quickActions: "Quick Dispatch Actions",
    resolutionNotes: "Resolution Action Taken"
  },
  ta: {
    title: "சிவிக்ஏஐ கோவை",
    subtitle: "நகர அவசரக்கால முடிவெடுக்கும் மற்றும் சம்பவ கட்டளை அமைப்பு",
    role: "தற்போதைய பொறுப்பு",
    dispatcher: "கட்டுப்பாட்டு அதிகாரி",
    responder: "களப் பணியாளர் (நொய்யல் ரோந்து)",
    admin: "கணினி நிர்வாகி",
    language: "மொழி",
    offlineMode: "இணையமில்லா பயன்முறை",
    online: "இணைய இணைப்பு & ஒத்திசைக்கப்பட்டது",
    offline: "இணையமில்லா நிலை",
    syncQueue: "ஒத்திசைவு வரிசை",
    syncSuccess: "மேகக்கணி ஒத்திசைவு வெற்றிகரமாக முடிந்தது!",
    incidents: "அவசரகாலங்கள்",
    activeIncidents: "செயலில் உள்ள சம்பவங்கள்",
    reported: "பதிவுசெய்யப்பட்டது",
    dispatched: "அனுப்பப்பட்டது",
    onScene: "களத்தில்",
    resolved: "தீர்க்கப்பட்டது",
    severity: "தீவிரம்",
    critical: "மிக ஆபத்தானது",
    high: "அதிகம்",
    medium: "நடுத்தர",
    low: "குறைவு",
    category: "வகை",
    flooding: "வெள்ளம் / நீர் தேக்கம்",
    fire: "தீ விபத்து",
    road_block: "சாலை அடைப்பு",
    medical: "மருத்துவ உதவி",
    power_outage: "மின் தடை",
    other: "இதர சம்பவம்",
    location: "இடம் / மைல்கல்",
    addIncident: "புதிய அவசர அறிக்கை தாக்கல் செய்க",
    incidentTitle: "சம்பவத்தின் தலைப்பு",
    description: "விரிவான விளக்கம்",
    assignedTo: "ஒதுக்கப்பட்ட குழு",
    reportNow: "அனுப்புதல் அறிக்கை சமர்ப்பி",
    useGPS: "நேரடி ஜிபிஎஸ் தரவு",
    aiCore: "சிவிக்ஏஐ தீர்வு மையம்",
    aiPlaceholder: "ஜெமினியிடம் கேளுங்கள்: 'பீளமேடு அவசரத்திற்கு யாரை அனுப்பலாம்?'",
    askAI: "செயற்கை நுண்ணறிவு ஆலோசனை",
    analytics: "கோயம்புத்தூர் செயல்திறன் பகுப்பாய்வு",
    chartsTitle: "நேரடி செயல்பாடுகள் தொலைஅளவியல்",
    widgets: "செயலில் உள்ள கண்காணிப்புக் கருவிகள்",
    chatTitle: "தந்திரோபாய செயல்பாடுகள் அரட்டை",
    chatPlaceholder: "குழுவிற்கு செய்தி அனுப்பவும்...",
    send: "அனுப்பு",
    exportPDF: "சூழ்நிலை அறிக்கையை பதிவிறக்கு (PDF)",
    notifications: "அவசர அனுப்பீட்டு விழிப்பூட்டல்கள்",
    noIncidents: "இந்த நிலையில் எந்த சம்பவங்களும் இல்லை.",
    unassigned: "குழு ஒதுக்கப்படவில்லை",
    allWidgets: "மாநகராட்சி டாஷ்போர்டு விட்ஜெட்டுகள்",
    saveWidgetSettings: "விட்ஜெட் கட்டமைப்பை சேமி",
    mapLegend: "கோயம்புத்தூர் வரைபடம்",
    weatherWidget: "நொய்யல் நீர்ப்பிடிப்பு வானிலை",
    recentActivity: "மத்திய கட்டளை பதிவுகள்",
    quickActions: "விரைவான அனுப்பீட்டு முறைகள்",
    resolutionNotes: "அவசரம் தீர்க்கப்பட்ட விபரம்"
  }
};

export const DEFAULT_WIDGETS: CustomWidget[] = [
  { id: "wid-map", type: "map_legend", title: "Coimbatore Area Overlay", visible: true },
  { id: "wid-weather", type: "weather", title: "Noyyal River Hydrology", visible: true },
  { id: "wid-activity", type: "activity_log", title: "Command Activity Stream", visible: true }
];
